---
- hosts: pi
  remote_user: pi
  tasks:
    - name: update and upgrade apt packages
      become: true #use sudo
      apt: 
          upgrade: yes
          update_cache: yes
          cache_valid_time: 86400 #1 day
          autoremove: yes
