version: "3.6"
services:
  arm-runner:
    image: klud/gitlab-runner
    container_name: arm-runner
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /home/pi/Documents/Docker/Containers/runner:/etc/gitlab-runner

  mosquitto:
    image: eclipse-mosquitto
    container_name: mosquitto
    restart: always
    ports:
      - 1883:1883
      - 9001:9001
    volumes:
      - /home/pi/Documents/Docker/Containers/mosquitto/config:/mosquitto/config
      - /home/pi/Documents/Docker/Containers/mosquitto/data:/mosquitto/data
      - /home/pi/Documents/Docker/Containers/mosquitto/log:/mosquitto/log
      
  requestrr:
    image: darkalfx/requestrr
    container_name: requestrr
    restart: always
    ports:
      - 4545:4545
    volumes:
      - /home/pi/Documents/Docker/Containers/requestrr:/root/config
  yacht:
    image: selfhostedpro/yacht
    container_name: yacht
    restart: always
    ports:
      - 8000:8000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /home/pi/Documents/Docker/Containers/yacht:/config

  portainer:
    image: portainer/portainer
    container_name: portainer
    command: -H unix:///var/run/docker.sock
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /home/pi/Documents/Docker/Containers/portainer:/data

  kitana:
    image: pannal/kitana:latest
    container_name: kitana
    restart: unless-stopped
    command: -B 0.0.0.0:31337 -P

  nginx:
    image: nginx
    container_name: nginx
    restart: always
    ports:
      - 83:80
    volumes:
      - /home/pi/Documents/Docker/Containers/web/config/www:/usr/share/nginx/html

  web:
    image: wdaan/wdaan.github.io:arm
    container_name: web
    restart: always

  proxy:
    image: jc21/nginx-proxy-manager:latest
    container_name: proxy
    restart: always
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    volumes:
      - /home/pi/Documents/Docker/Containers/proxy/config.json:/app/config/production.json
      - /home/pi/Documents/Docker/Containers/proxy/data:/data
      - /home/pi/Documents/Docker/Containers/proxy/letsencrypt:/etc/letsencrypt
    environment:
      DISABLE_IPV6: 'true'

  ouroboros:
    container_name: ouroboros
    hostname: ouroboros
    image: pyouroboros/ouroboros
    environment:
      - CLEANUP=true
      - INTERVAL=86400 #24 hours
      - LOG_LEVEL=info
      - SELF_UPDATE=true
      - IGNORE="nginx proxy"
      - TZ=Europe/Brussels
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock